import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Mono, Josefin_Sans } from 'next/font/google'
import Header from '@/components/header';



const ibm = IBM_Plex_Mono({ weight: '300', subsets: ['latin'], variable: '--font-ibm' })
const josefin = Josefin_Sans({ weight: '700', subsets: ['latin'], variable: '--font-josefin' })

export const metadata: Metadata = {
  title: 'Anne-Flore Bernard',
  description: 'Portfolio de développeuse fullstack créative.',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${ibm.variable} ${josefin.variable} bg-background text-primary `}
        >
        <Header />
        {children}
      </body>
    </html>
  )
}


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
